#!/bin/bash
echo "Setting up werkstation on profile $PROFILE. Ctrl+C to abort."

sleep 6

cd /workspace

if [ -n "$SSH_AUTH_SOCK" ]; then
    echo "SSH agent is running and attached."
    
else
    echo "No SSH agent is attached. Be sure to connect via ssh with flags `-At` to enable agent forwarding"
    exit(1)
fi
git clone https://github.com/nola-ai/werkstation
cd /workspace/werkstation
make "${PROFILE}"
